name: .NET

on:
  push:
    branches: [ local-deploy-to-ubuntu-apache ]
  pull_request:
    branches: [ local-deploy-to-ubuntu-apache ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet publish
      run: dotnet publish -c Release -o webapp
    - name: Move publish directory
      run: mv webapp windows-lb\userdata\
    - name: Write API access key
      run: mkdir ~/.oci && echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/oci_api_key.pem
    - name: Write instance access key
      run: mkdir ~/.ssh && echo "${{secrets.OCI_INSTANCE_FILE}}" >> ~/.oci/oci_instance
    - name: Assign key to environment variable
      run: OCI_INSTANCE_KEY=$(cat ~/.oci/oci_instance)
    - name: Print instance key
      run: echo $OCI_INSTANCE_KEY
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
    - name: Perform terraform apply
      run: cd windows-lb && terraform init && terraform apply -auto-approve
    - name: Get host username and IP
      run: $hostuserip =("ubuntu@" + $(terraform output --raw public_ip))
    - name: Print user name and IP
      run: echo $hostuserip
